### ISSUE TITLE
Player is banned but is showed not banned on panel

### ISSUE THREAD

**Issue by Spazzinq** [mathhulk/ab-web-addon#24]
![image](https://user-images.githubusercontent.com/26337405/32411104-2322b89e-c1a9-11e7-86eb-06d217358f59.png)

I did not remove the ban. If you need more info, pm me on discord :P

**Comment by mathhulk** [comment]
Can you make sure that the ban you show in that picture is actually in both database tables. In order to check if a ban is active, ab-web-addon selects the ban in the PunishmentHistory table and then checks to see if the exact ban is available in the Punishments table. I don't seem to be having any problems with this on https://www.mathhulk.com/github/ab-web-addon/.

**Comment by Spazzinq** [comment]
It is on both tables.

**Comment by Megamezzomixer** [comment]
Hello there.
I have reported the same issue on Spigot recently and I got redirected here.

Our temporary bans/mutes/warns are shown as inactive everytime. Even if the temporary punishment is still active.
I'll provide some screenshots:
https://megamezzomixer.de/screens/2017-11-11_14-20-33.png // This is the database entry. This entry is exactly equal on both tables.

https://megamezzomixer.de/screens/2017-11-11_14-22-17.png // This is the webinterface.
(I have colored the inactive and active word depending on the status, but this doesn't affect the bug. I have tested that already.)

**Comment by mathhulk** [comment]
This has hopefully been fixed in the latest update.

**Comment by Spazzinq** [comment]
Yep 👍
