### ISSUE TITLE
Player Heads bug

### ISSUE THREAD

**Issue by lucas2107** [mathhulk/ab-web-addon#35]
Just take a look at this screen ^^ http://prntscr.com/hrer71

**Comment by mathhulk** [comment]
Player heads seem to be really buggy. This is mostly because all of the APIs that I have been trying have been unreliable or dead. You can change the APIs using their URLs where you change the database credentials. I would suggest trying to find a reliable API first, as I don't think this problem is caused by ab-web-addon itself and instead is just an issue of using unreliable APIs.

**Comment by lucas2107** [comment]
Maybe you can try this: https://crafatar.com/

**Comment by lucas2107** [comment]
Surgeplay API: 13.5s for loading
Crafatar: 9s for loading

Tested on the same page. One problem: heads are too big :/
